services:
  docker_compose_angular_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker_compose_angular_app
    ports:
      - "4200:80"
    networks:
      - angular-app-network

networks:
  angular-app-network:
    driver: bridge
